export const productCardData =[
    { 
        id:1,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/kovacs__mate-JrnAy5sR6Kg-unsplash.jpg?v=1694168259',
        product:'All-in-one Computers'
    },
    { 
        id:2,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/aryan-dhiman-iGLLtLINSkw-unsplash.jpg?v=1694084625',
        product:'Best Details'
    },
    { 
        id:3,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/lucian-alexe-yh0UtueiZ-I-unsplash.jpg?v=1694089662',
        product:'Cabels'
    },
    { 
        id:4,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/benjamin-raffetseder-HDIUUSO5C8g-unsplash.jpg?v=1694152834',
        product:'Cameras'
    },
    {  
        id:5,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/screen-post-JF0R2sMFbJU-unsplash_1.jpg?v=1694088441',
        product:'Chargers'
    },
    { 
        id:6,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/nathan-dumlao-sW_10braKvE-unsplash.jpg?v=1694089022',
        product:'Chromeboks'
    },
    { 
        id:7,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/onur-binay-4Ykxp_t4i08-unsplash.jpg?v=1693293933',
        product:'Accessories'
    },
    { 
        id:8,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/marvin-meyer-SYTO3xs06fU-unsplash.jpg?v=1693908760',
        product:'Laptop'
    },
    { 
        id:9,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/erik-gazi-RPUXMWbwP7M-unsplash.jpg?v=1694153779',
        product:'Coolers'
    },
    { 
        id:10,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/kelly-sikkema-2d-ZQjDhH94-unsplash.jpg?v=1693308618',
        product:'Creatives'
    },
    { 
        id:11,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/balkouras-nicos-ncOQxZe8Krw-unsplash.jpg?v=1694090263',
        product:'Desktop Computers'
    },
    { 
        id:12,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/cece-kun-C_E47HYN8EY-unsplash.jpg?v=1694152637',
        product:'Draving Tables'
    },
    { 
        id:13,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/davide-boscolo-gz9njd0zYbQ-unsplash.jpg?v=1693899042',
        product:'Electronics'
    },
    { 
        id:14,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/tom-pumford-v8ppsvUTwGE-unsplash.jpg?v=1694150168',
        product:'Flash Drives'
    },
    { 
        id:15,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/igor-karimov-fXmmSz5KkO8-unsplash.jpg?v=1694153873',
        product:'Gamepads'
    },
    { 
        id:16,
        img:'https://multi-themes.myshopify.com/cdn/shop/collections/joseph-greve-D_1-g2eLho8-unsplash.jpg?v=1694089184',
        product:'Grapics Card'
    },
]